config/routes.rb
Questioncollab::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  root :to => "questions#index"
  resources :questions do
    resources :users
 end

end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
  attr_accessible :answer

  belongs_to :user
  belongs_to :question

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :answer, :category, :title
  has_many :authorships
  has_many :users, through: :authorships
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :authorships
  has_many :questions, through: :authorships

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
    end
  end
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

def all
  user = User.from_omniauth(request.env["omniauth.auth"])
  if user.persisted?
    flash.notice = "Signed in!"
    sign_in_and_redirect user
  else
    session["devise.user_attributes"] = user.attributes
    redirect_to new_user_registration_url
  end
end
  alias_method :twitter, :all

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
before_filter :authenticate_user!, :except => [:index, :show]
before_filter :find_question, :only => [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all

  end

  def show

  end

  def new
    @question = Question.new
  end

  def create
     @question = Question.new(params[:question])
    if @question.save
      #current_user.questions |= @question
      @question.users << current_user unless current_user.in?@question.users

    #if @question = current_user.questions.create(params[ :question])
       #@question.users.create(params[ :user])

      flash[ :notice] = "Question has been created."
      redirect_to @question
    else
      flash[ :alert] = "Question has not been created."
      render :action => "new"
    end
  end
  def edit

  end

  def destroy
    @question.destroy
    flash[:notice] = "Question has been deleted."
    redirect_to questions_path
  end

  def update
    @question.update_attributes(params[:question])
    @question.users << current_user unless current_user.in?@question.users
    flash[:notice] = "Question has been updated."
    redirect_to [@question]
  end

  private
    def find_question
      @question = Question.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The question you were looking" +
            " for could not be found."
      redirect_to questions_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @question = Question.find(params[:question_id])
    @user = @question.users.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Questioncollab</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
     <%= value %>
  </div>
<% end %>
<nav>
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>
  <% end %>
</nav>
<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<h2>Edit Question</h2>

<%= form_for(@question) do |f| %>
  <p>
    <%= f.label :title %> <br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </p>

  <p>
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </p>

  <%= f.submit %>
<% end %>

app/views/questions/index.html.erb
<h2>All Questions</h2>
<ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.title, question %> </li>
  <% end %>
</ul>

<%= link_to "New Question", new_question_path %>

app/views/questions/new.html.erb
<h2>New Question</h2>

<%= form_for(@question) do |f| %>
  <p>
    <%= f.label :title %> <br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </p>

  <p>
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </p>

  <%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<h2>Question</h2>
<h2>Question: <%= @question.title %></h2>
<h2>Answer: <%= @question.answer %></h2>
<h2>Category: <%=@question.category %></h2>

<h2>Users</h2>
<ul id='users'>
  <% @question.users.each do |user| %>
    <li>
      #<%= user.id %> -
      <%= link_to user.email, [@question, user] %>
    </li>
   <% end %>
</ul>

<%= link_to "Edit Question", [:edit, @question] %>
<%= link_to "Delete Question", [@question], :method => :delete, :confirm => "Are you sure you want to delete this question?" %>
<%= link_to "View Questions", root_path %>

app/views/users/show.html.erb
<h3>Edited Questions by <%= @user.email %></h3>
<ul>
  <% @user.questions.each do |q| %>
    <li>
      #<%= q.id %> -
      <%= link_to q.title, q %>
    </li>
   <% end %>
</ul>
<%= link_to "Back to Questions", root_path %>